apps/rubro/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "rubros"

urlpatterns = [
    path('listar/', views.ListarRubros.as_view(), name="listar"),
    path('detalle/<int:pk>', views.DetalleRubro.as_view(), name="detalle"),
    path('agregar/', views.AgregarRubro.as_view(), name="agregar"),
    path('modificar/<int:pk>', views.ModificarRubro.as_view(), name="modificar"),
    path('eliminar/<int:pk>', views.EliminarRubro.as_view(), name="eliminar"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #URLS admin
    path('admin/', admin.site.urls),

    #URLS PRINCIPALES
    path('', views.ListarRubrosHome.as_view(), name="start"),

    #URLS LOGIN AND LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    #URLS PARA REDIRECCIONAR
    path('productos/', include('apps.productos.urls')),
    path('rubros/', include('apps.rubro.urls')),
    path('favorite/', include('apps.favorite.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/rubro/models.py
from django.db import models

class Rubro(models.Model):
	nombre = models.CharField(max_length=30)
	descripcion = models.CharField(max_length=200)
	def __str__(self):
		return self.nombre
# Create your models here.

apps/rubro/views.py
from django.shortcuts import render, redirect
from .models import Rubro
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

class ListarRubros(LoginRequiredMixin,ListView):
	model = Rubro
	template_name = 'Rubro/listarRubros.html'

class DetalleRubro(LoginRequiredMixin,DetailView):
	model = Rubro
	template_name = 'Rubro/detalle.html'

class AgregarRubro(LoginRequiredMixin,CreateView): #Vistas basadas en clases
	model = Rubro
	template_name = 'Rubro/agregar.html'
	success_url = reverse_lazy('rubros:listar')
	fields = '__all__'

class ModificarRubro(LoginRequiredMixin,UpdateView):
	model = Rubro
	template_name = 'Rubro/agregar.html'
	success_url = reverse_lazy('rubros:listar')
	fields = '__all__'

class EliminarRubro(LoginRequiredMixin,DeleteView):
	model = Rubro
	template_name = 'Rubro/eliminar.html'
	success_url = reverse_lazy('rubros:listar')

templates/Rubro/agregar.html
{% extends 'base.html' %}

	{% block contenido %}
		<div class="row">
			<div class="col-4"></div>

			<div class="col-4 mt-4">
				<form class="shadow p-3 mb-3 mt-3 bg-white rounded" enctype="multipart/form-data"  method="POST"> {% csrf_token %}
					<div class="d-flex justify-content-center mt-2 mb-2">
						<img src="https://www.fangazing.com/imgfiles/Fangazing2017/img/xnuevo.png.pagespeed.ic.O4O1059s6n.png" class="img-top" height="100" width="200">
					</div>

					{{ form.as_p }}

				 	<div class="d-flex justify-content-between mt-2">
				 		<div>
				 			<button type="submit" class="btn btn-secondary"><a class="text-white" href="{% url 'rubros:listar' %}">Cancel</a></button>
				 			<button type="submit" class="btn btn-success">Guardar</button>
				 		</div>
				 		{% if object %}
				 		<div>
				 			<a type="submit" href="{% url 'rubros:eliminar' object.pk %}" class="btn btn-danger">Eliminar</a>
				 		</div>
				 		<div class="mt-5 mb-5">
				 			
				 		</div>
				 		{% endif %}
				 	</div>
				</form>
			</div>

			<div class="col-4"></div>
			
		</div>
	{% endblock contenido %}

templates/Rubro/detalle.html
{% extends 'base.html' %}

	{% block contenido %}

	<div class="row">


		<div class="col-4 d-flex justify-content-center">
			<div class="card mt-4" style="width: 18rem;">
				<div class="card-body">
					<h5 class="card-title">{{object.nombre}}</h5>
					<p class="card-text">Descripción: {{object.descripcion}}</p>
				</div>
			</div>
		</div>

		<div class="col-4">
		</div>

	</div>

	{% endblock contenido %}

templates/Rubro/eliminar.html
{% extends 'base.html' %}

	{% block contenido %}

	<form method="POST">
		{% csrf_token %}
		<div class="alert alert-danger mt-5 ml-3 mr-3" role="alert">Estas seguro que quieres eliminar el rubro {{ object.nombre }}?</div>
		<button class="btn btn-danger ml-3" type="submit">Si</button>
	</form>



	{% endblock contenido %}

templates/Rubro/listarRubros.html
{% extends 'base.html' %}

	{% block contenido %}

		<div class="row d-flex justify-content-between align-items-center ml-3 mr-3">
			<h1 class="text-muted">Rubros</h1>
			<span class="d-flex align-items-center">
					{{ object_list|length }} resultados.
			</span>
			<button type="button" class="btn btn-success mb-2 mt-2 ml-2 mr-2"><a class="text-light" href="{% url 'rubros:agregar' %}">Agregar Rubro +</a></button>
		</div>

		<div class="card-deck ml-2 mr-2 pb-5">
			
			{% for p in object_list %}

				<div class="card mb-3 shadow-sm bg-white rounded" style="max-width: 200px;">
				    		<div class="card-header">
				    			<a href="{% url 'rubros:detalle' p.pk %}"><h3 class="card-title text-secondary">{{p.nombre}}</h3></a>
				    		</div>
				    		<div class="card-body">
								<a href="{% url 'rubros:modificar' p.pk %}">
				    				<span>Modificar</span>
				    			</a>
				    		</div>
				</div>

			
				
			{% endfor%}	
		</div>

	{% endblock contenido %}