apps/favorite/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "favorite"

urlpatterns = [

    path('agregar/<int:pk>', views.AddFavorite, name="agregar"),
    
]

apps/productos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "productos"

urlpatterns = [
    path('detalle/<int:pk>', views.DetalleProducto.as_view(), name="detalle"),
    path('agregar/', views.AgregarProducto.as_view(), name="agregar"),
    path('modificar/<int:pk>', views.ModificarProducto.as_view(), name="modificar"),
    path('eliminar/<int:pk>', views.EliminarProducto.as_view(), name="eliminar"),
    path('productos/', views.ListarProductosPorRubro.as_view(), name="porrubro"),
]

apps/rubro/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "rubros"

urlpatterns = [
    path('listar/', views.ListarRubros.as_view(), name="listar"),
    path('detalle/<int:pk>', views.DetalleRubro.as_view(), name="detalle"),
    path('agregar/', views.AgregarRubro.as_view(), name="agregar"),
    path('modificar/<int:pk>', views.ModificarRubro.as_view(), name="modificar"),
    path('eliminar/<int:pk>', views.EliminarRubro.as_view(), name="eliminar"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #URLS admin
    path('admin/', admin.site.urls),

    #URLS PRINCIPALES
    path('', views.ListarRubrosHome.as_view(), name="start"),

    #URLS LOGIN AND LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    #URLS PARA REDIRECCIONAR
    path('productos/', include('apps.productos.urls')),
    path('rubros/', include('apps.rubro.urls')),
    path('favorite/', include('apps.favorite.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/productos/models.py
from django.db import models
from apps.rubro.models import Rubro

# Create your models here.

class Productos(models.Model):
	nombre = models.CharField(max_length=30)
	precio = models.DecimalField(max_digits=8, decimal_places=2)
	stock = models.IntegerField()
	imagen = models.ImageField(upload_to = 'productos', null = True)
	rubro = models.ForeignKey(Rubro, on_delete=models.CASCADE, related_name='productosXrubro')

	def __str__(self):
		return self.nombre

apps/productos/forms.py
from django import forms
from .models import Productos

class ProductosForm(forms.ModelForm):
	class Meta:
		model = Productos
		fields = ['nombre', 'precio', 'stock', 'imagen']

apps/productos/views.py
from django.shortcuts import render, redirect
from .models import Productos, Rubro
from apps.favorite.models import Favorite
from .forms import ProductosForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# Create your views here.

'''def ListarProductos(request):
	p  = Productos.objects.all()
	pp = Productos.objects.filter(stock=10)
	ppp = Productos.objects.get(pk = 1)
	context = {}
	context['Productos'] = p
	context['Cantidad'] = p.count()
	return render(request, 'Productos/listarProductos.html',context)'''

class ListarProductos(LoginRequiredMixin,ListView):
	model = Productos
	template_name = 'Productos/listarProductos.html'

'''@login_required
def ListarProductosPorRubro(request, rubro):
	context = {}
	context['object_list'] = Productos.objects.filter(rubro = rubro)
	
	#r = Rubro.objects.get(pk=rubro)
	#context['object_list'] = r.productosXrubro.all()
	#return render(request, 'Productos/listarProductos.html', context)
	
	return render(request, 'Productos/listarProductos.html', context)'''

class ListarProductosPorRubro(LoginRequiredMixin, ListView):

	template_name = 'Productos/listarProductos.html'

	def get_queryset(self):
		onlyDisp = self.request.GET.get('disponibles')
		desde = self.request.GET.get('desde', None)
		hasta = self.request.GET.get('hasta', None)
		rubro = self.request.GET.get('filtro', None)

		if not rubro:
			rubro = "0"
		
		if not desde:
			desde = 0
		if not hasta:
			hasta = 9999999999

		if rubro == "0":
			if onlyDisp == "si":
				x = Productos.objects.filter(stock__gt = 0, precio__gte = desde, precio__lte = hasta)
			else:
				x = Productos.objects.filter(precio__gte = desde, precio__lte = hasta)
		else:
			if onlyDisp == "si":
				x = Productos.objects.filter(rubro = rubro, stock__gt = 0, precio__gte = desde, precio__lte = hasta)
			else:
				x = Productos.objects.filter(rubro = rubro, precio__gte = desde, precio__lte = hasta)	
		return x

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['rubros'] = Rubro.objects.all()

		favorites = Favorite.objects.filter(user = self.request.user).values('producto')

		fav = []
		for p in context['object_list']:
			for i in favorites:
				if p.pk == i['producto']:
					fav.append(p.pk)

		context['favList'] = fav
		
		rubro = self.request.GET.get('filtro', None)
		if not rubro:
			rubro = "0"
		print("Rubro: ", rubro)
		if rubro == "0":
			context['rubroUnico'] = "Todos"
		else:
			context['rubroUnico'] = Rubro.objects.get(id = rubro).nombre
		return context


'''def DetalleProducto(request,codigo):
	context = {}
	context['Productos'] = Productos.objects.get(pk = codigo)
	return render(request, 'Productos/detalle.html',context)'''

class DetalleProducto(LoginRequiredMixin,DetailView):
	model = Productos
	template_name = 'Productos/detalle.html'

'''def AgregarProducto(request): #Vistas basadas en funciones
	form = ProductosForm(request.POST or None, request.FILES)

	if form.is_valid():
		form.save()
		return redirect('productos:listar')

	return render(request, 'Productos/agregar.html', {'form': form})'''

class AgregarProducto(LoginRequiredMixin,CreateView): #Vistas basadas en clases
	model = Productos
	template_name = 'Productos/agregar.html'
	success_url = reverse_lazy('productos:porrubro')
	fields = '__all__'

'''def ModificarProducto(request, codigo):
	producto = Productos.objects.get(id=codigo)
	form = ProductosForm(request.POST or None, request.FILES or None, instance=producto)

	if form.is_valid():
		form.save()
		return redirect('productos:listar')'''

class ModificarProducto(LoginRequiredMixin,UpdateView):
	model = Productos
	template_name = 'Productos/agregar.html'
	success_url = reverse_lazy('productos:porrubro')
	fields = '__all__'

'''def EliminarProducto(request, codigo):
	producto = Productos.objects.get(id=codigo)

	if request.method == 'POST':
		producto.delete()
		return redirect('productos:listar')

	return render(request, 'Productos/eliminar.html', {'Productos':producto})'''

class EliminarProducto(LoginRequiredMixin,DeleteView):
	model = Productos
	template_name = 'Productos/eliminar.html'
	success_url = reverse_lazy('productos:porrubro')

templates/Productos/agregar.html
{% extends 'base.html' %}

	{% block contenido %}
		<div class="row">
			<div class="col-4"></div>

			<div class="col-4 mt-4">
				<form class="shadow p-3 mb-3 mt-3 bg-white rounded" enctype="multipart/form-data"  method="POST"> {% csrf_token %}
					<div class="d-flex justify-content-center mt-2 mb-2">
						<img src="https://www.fangazing.com/imgfiles/Fangazing2017/img/xnuevo.png.pagespeed.ic.O4O1059s6n.png" class="img-top" height="100" width="200">
					</div>

					{{ form }}

				 	<div class="d-flex justify-content-between mt-2">
				 		<button type="submit" class="btn btn-secondary"><a class="text-white" href="{% url 'productos:listar' %}">Cancel</a></button>
				 		<button type="submit" class="btn btn-success">Guardar</button>
				 		{% if Productos %}
				 		<a type="submit" href="{% url 'productos:eliminar' Productos.pk %}" class="btn btn-danger">Eliminar</a>
				 		{% endif %}
				 	</div>
				</form>
			</div>

			<div class="col-4"></div>
			
		</div>
	{% endblock contenido %}

templates/Productos/detalle.html
{% extends 'base.html' %}

	{% block contenido %}

	<div class="row">


		<div class="col-4 mt-3">
			<div class="card" style="width: 18rem;">
				{% if object.imagen.url != null %}
				<img src="{{object.imagen.url}}" class="card-img-top" alt="...">
				{% else %}
				<img src="https://www.construmart.cl/tiendaonline/images/site/no-disponible.png" class="card-img-top" alt="...">
				{% endif %}
				<div class="card-body">
					<h5 class="card-title">{{object.nombre}}</h5>
					<p class="card-text">Precio: ${{object.precio}}</p>
				</div>
				<ul class="list-group list-group-flush">
					<li class="list-group-item">Stock: {{object.stock}}</li>
					<li class="list-group-item">Rubro: {{object.rubro}}</li>
				</ul>
				<div class="card-body">
					<span>Disponible: {% if object.stock > 0 %}
						Si
					{% else %}
						No
					{% endif %}
					</span>
				</div>
			</div>
		</div>

		<div class="col-4">
		</div>

	</div>

	{% endblock contenido %}

templates/Productos/eliminar.html
{% extends 'base.html' %}

	{% block contenido %}

	<form method="POST">
		{% csrf_token %}
		<div class="alert alert-danger" role="alert">Estas seguro que quieres eliminar el producto {{ producto.nombre }}?</div>
		<button type="submit">Si</button>
	</form>


	{% endblock contenido %}

templates/Productos/listarProductos.html
{% extends 'base.html' %}
	{% load static %}
	{% block contenido %}

		<div class="row d-flex justify-content-between align-items-center ml-3 mr-3">
			<div class="d-flex justify-content-start text-muted">
				
				<h1>{{rubroUnico}}</h1>
				
			</div>
			<div>
				<span class="d-flex align-items-center">
					{{ object_list|length }} resultados.
				</span>
			</div>
			<div clas="col-12 mt-3 mb-3 ml-5">

				<form action="">
					<div class="d-flex justify-content-center align-items-center">
						<select name="filtro" class="custom-select">							
							<option value="0">Todos los Rubros</option>
							{% for p in rubros %}
								<option value='{{p.pk}}'>{{p.nombre}}</option>
							{% endfor %}
							
						</select>
						<button type="submit" class="ml-2 btn-sm btn btn-secondary">Filtrar</button>
					</div>
				</form>
			</div>
			<div>
				<form action="">
					<div class="d-flex justify-content-center align-items-center">
					<select name="disponibles" id="" class="custom-select">
						<option value="no">Todos los Productos</option>
						<option value="si">Disponibles</option>
					</select>
					<button type="submit" class="ml-2 btn-sm btn btn-secondary">Filtrar</button>
					</div>
				</form>
			</div>
			<div>
				<button type="button" class="btn btn-success mb-2 mt-2 ml-2 mr-2"><a class="text-light" href="{% url 'productos:agregar' %}">Agregar Producto +</a></button>
			</div>
		</div>
		
		<div class="row">
			<div class="col-2">
				<form class="ml-3 mt-2">
					<label for="">Filtro por precio ($)</label>

					<input type="number" name="desde" placeholder="desde">
					<input type="number" name="hasta" placeholder="hasta">
		
					<div class="mt-2">
						<button type="submit" class="btn-sm btn btn-secondary"> Filtrar </button>
					</div>					
				</form>
			</div>
			<div class="col-10">
				<div class="card-deck mr-2 pb-4 bg-white rounded-lg">
					
					{% if not object_list|length %}
							<h3 class="ml-3 mt-2"><label class="text-secondary" for="">No hay resultados</label></h3>
						{% endif %}

					{% for p in object_list %}
						<div class="card mb-3 shadow-sm bg-gradient-light rounded d-flex align-items-center" style="min-width: 300px; 
						background-color: rgba(124, 124, 124, .4);">
					
							<div class="row no-gutters d-flex align-items-center" style="height:100%">
						    	<div class="col-md-4 d-flex align-items-stretch">
						    	{% if p.imagen %}
						    		<img src="{{p.imagen.url}}" class="card-img" alt="...">
						    	{%endif%}
						    	</div>

						    	<div class="col-md-8">
						    		<div class="card-body">
						    			<a href="{% url 'productos:detalle' p.pk %}"><h6 class="card-title">{{p.nombre}}</h6></a>

						    			<label class="card-text"><small>Stock: {% if p.stock > 0 %} {{p.stock}} {% endif %} {% if p.stock <= 0 %} <p class="text-danger"> No disponible</p> {% endif %}</small></label> 
						    			<div>
						    				<label class="card-text"><small class="text-muted">$ {{p.precio}}</small></label>
						    				<a class="ml-2 mr-2" href="{% url 'productos:modificar' p.pk %}"><img width="15" src="{% static 'img/edit.svg' %}" alt=""></a>
							    			{% if p.pk in favList %}
							    				<a href="{% url 'favorite:agregar' p.pk %}"><img width="20" src="{% static 'img/fav.svg' %}" alt=""></a>
							    			{% else %}	
							    				<a href="{% url 'favorite:agregar' p.pk %}"><img width="20" src="{% static 'img/noFav.svg' %}" alt=""></a>
							    			{% endif %}
							    		</div>
						    		</div>
						  		</div>
							</div>
						</div>

				
					{% endfor%}	
				</div>
			</div>
		</div>

	{% endblock contenido %}