apps/productos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "productos"

urlpatterns = [
    path('detalle/<int:pk>', views.DetalleProducto.as_view(), name="detalle"),
    path('agregar/', views.AgregarProducto.as_view(), name="agregar"),
    path('modificar/<int:pk>', views.ModificarProducto.as_view(), name="modificar"),
    path('eliminar/<int:pk>', views.EliminarProducto.as_view(), name="eliminar"),
    path('productos/', views.ListarProductosPorRubro.as_view(), name="porrubro"),
]

apps/rubro/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "rubros"

urlpatterns = [
    path('listar/', views.ListarRubros.as_view(), name="listar"),
    path('detalle/<int:pk>', views.DetalleRubro.as_view(), name="detalle"),
    path('agregar/', views.AgregarRubro.as_view(), name="agregar"),
    path('modificar/<int:pk>', views.ModificarRubro.as_view(), name="modificar"),
    path('eliminar/<int:pk>', views.EliminarRubro.as_view(), name="eliminar"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #URLS admin
    path('admin/', admin.site.urls),

    #URLS PRINCIPALES
    path('', views.ListarRubrosHome.as_view(), name="start"),

    #URLS LOGIN AND LOGOUT
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

    #URLS PARA REDIRECCIONAR
    path('productos/', include('apps.productos.urls')),
    path('rubros/', include('apps.rubro.urls')),
    path('favorite/', include('apps.favorite.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link rel="shortcut icon" href="{% static 'img/icon.png' %}" type="icon/png">
	<title>Blog Ema</title>
</head>
<body>
	<div class="container-fluid" style="background-color: rgb(219, 219, 219)">
		

		<div class="row">
			<div class="col-4 nav">
				<div style="margin: 10px" class="d-flex align-items-center">
					{% if user.is_authenticated %}
						<b class="text-light mr-2">Hola, {{user.username}}!</b>
						<a href="{% url 'logout' %}"><img class="ml-2" src="{% static 'img/poweroff.png' %}" width="20" alt="logout" title="Logout"></a>
					{% else %}
						<a href="{% url 'login' %}">Login</a>
					{% endif %}
				</div>	
			</div>	
			<div class="col-4 nav d-flex justify-content-center">
				<button type="button" class="mt-2 mb-2 btn btn-sm " onClick="location.href='{% url 'start' %}'"><img class="" src="{% static 'img/home.png' %}" alt="" width="30"></i></button>
			</div>			
			
			<div class="col-4 nav d-flex justify-content-end">
				<a href="#"><img  height = '50' width = '200' src="https://media.flaticon.com/dist/min/img/logo/freepikcompany.svg" /></a>
			</div>
		</div>

		<div class="contenido" style="min-height: 550px">
		{% block contenido %}

		{% endblock contenido %}
		</div>

		<div class="row">
			<div class="col-12 foot">
				<p style="margin: 20px">Footer</p>
			</div>
		</div>

	</div>
	
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
	<title>Log In</title>
</head>
<body>
	<div class="container-fluid" >
		
		<div class="row">

			<div class="col-6">
				<div class="row d-flex justify-content-center align-items-center" style="background-image: url('https://st2.depositphotos.com/1244201/8876/i/950/depositphotos_88764972-stock-photo-black-abstract-background.jpg');">
					<img height="667" src="" alt="">
					<h1 class="text-light font-weight-light">Django Project <span class="badge badge-info font-weight-light">New</span></h1>
				</div>
			</div>

			<div class="col-6" height="667">
				<div class="row d-flex justify-content-center align-items-center">
					<div class="card shadow-lg p-3 mb-5 rounded" style="margin-top: 12%;">
						<div class="card-header d-flex justify-content-center bg-white">
							<img clas="card-img-top" src="https://amcrest.ca/media/catalog/product/cache/1/image10/225x150/9df78eab33525d08d6e5fb8d27136e95/i/p/ipm-721_2_10.png" alt="">	
						</div>
						<div class="card-body">
							{% if form.errors %}
								<div class="alert" style="background-color: red;"> {{form.errors}} </div>
							{% endif %}
							<form action="{% url 'login' %}" method="POST">{% csrf_token %}
								<div class="form-group">
								    <label for="exampleInputEmail1">Username</label>
								    <input type="text" class="form-control" name="username" aria-describedby="emailHelp" placeholder="Enter username">
								    <small id="emailHelp" class="form-text text-muted">We'll never share your username with anyone else.</small>
								  </div>
								  <div class="form-group">
								    <label for="exampleInputPassword1">Password</label>
								    <input type="password" class="form-control" name="password" placeholder="Password">
								  </div>
								  <input type="hidden" name="next" value="{{ next }}" />

								  <button type="submit" class="btn btn-primary">Submit</button>
							</form>
						</div>				
					</div>
				</div>				
			</div>

		</div>

	</div>


</body>
</html>

templates/start.html
{% extends 'base.html' %}

	{% block contenido %}
	<div class="container-fluid pb-1 pt-1" >
		<div class="row mt-3 mb-3 ml-5">
			<h1><strong>BIENVENIDOS AL SISTEMA DE PRODUCTOS ER1</strong></h1>
		</div>
		
		<div class="row d-flex justify-content-center">
			<div clas="col-12 mt-3 mb-3 ml-5">
				<button type="button" class="btn boton mt-2 ml-2"><a class="text-white" href="{% url 'productos:porrubro' %}">Ver Productos</a></button>

				<button type="button" class="btn boton mt-2 ml-2"><a class="text-white" href="{% url 'rubros:listar' %}">Ver Rubros</a></button>
			</div>
		</div>

		<div>
			
		</div>

	</div>
	{% endblock contenido %}